version: '3.3'
services:
  web:
    restart: always
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: arispontcrates_php_74
    depends_on:
      - db
    ports:
      - ${web_port}:80
    environment:
      - mysql_password=${mysql_password}
  db:
    restart: always
    container_name: arispontcrates_mysql8
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_password}
      MYSQL_DATABASE: arispontcrates
      MYSQL_USER: arispontcrates_user
      MYSQL_PASSWORD: ${mysql_password}
    ports:
      - ${db_port}:3306
    volumes:
      - ./db_data:/var/lib/mysql
      - ./php/conf_server/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    restart: always
    container_name : arispontcrates_phpmyadmin
    image: phpmyadmin/phpmyadmin:5
    environment:
      PMA_HOST: db
    ports:
      - ${phpmyadmin_port}:80
    depends_on:
      - db 