/*CREATE DATABASE `arispontcrates`;*/

CREATE TABLE `arispontcrates`.`familles`(
    `Nom` VARCHAR(80),`Prenom` VARCHAR(20),
    `Famille` VARCHAR(10)) 
    ENGINE = InnoDB DEFAULT CHARSET=utf8;
    /*ENGINE = MyISAM;*/

CREATE TABLE `arispontcrates`.`ptidej` (
    `user_id` INT NOT NULL AUTO_INCREMENT ,
    `prenom` VARCHAR(264) NOT NULL , 
    `nom` VARCHAR(264) NOT NULL , 
    `telephone` INT(255) NOT NULL , 
    `res` VARCHAR(264) NOT NULL , 
    `appartement` VARCHAR(264) NOT NULL , 
    `autre_adresse` VARCHAR(264) NOT NULL , 
    `heure` VARCHAR(264) NOT NULL , 
    `tartine` VARCHAR(264) NOT NULL , 
    `viennoiserie` VARCHAR(264) NOT NULL , 
    `Sale` VARCHAR(264) NOT NULL , 
    `boisson` VARCHAR(264) NOT NULL , 
    `jus` VARCHAR(264) NOT NULL , 
    `commentaire` VARCHAR(264) NOT NULL , 
    PRIMARY KEY (`user_id`))
    ENGINE = InnoDB DEFAULT CHARSET=utf8; 
    /*ENGINE = MyISAM;*/


INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ABOUANASS','Scenwan','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('AIRAUD','Audrey','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ARULPRAGASAM','Steven','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ATTALI','Aurélia','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BABI','Mohamed Yacine','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BAGNIS','Tristan','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BAILLARD','Adeline','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BARBEDOR','Esther-Anne','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BÉGUET','Carla','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BEKKALI','Lina','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BELIN-BOURGOGNE','Emile','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BEN DJELLOUN TOUIMI','Reda','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BERANGER','Sophie','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BERNIER','Julien','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BIETH','Guillaume','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BILLON','Juliana','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BINDER','Sacha','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BLOTAS','Simon','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BONA','Nada','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BORGES','Alexandre','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BOU OBEID','Ryan','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BOUCHEREAU','Yann','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BOUKOBZA','Esther','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BOUSSEMARD','Martin','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BRESNU','Arthur','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BUSCH','Nicolas','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BUTSANETS','Léo','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CAMBIER','Lucien','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CANTINI','Clotilde','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CARREAUD','Hugo','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CASTRES','Yann','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CASTRO','Sullivan','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CATTEAU','Maxence','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CHANDRU','Vincent','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CHAUSSADE','Pierre','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CHENGUEL','Ayoub','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CHEVRIE','Yann','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CHOTARD','Alexandre','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('COHEN-SOLAL','Maxime','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('COLLET','Jeanne','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CONTENTIN','Théo','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CORBEL','Alban','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CORVOL','Nicolas','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CREPY','Louis','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CROS','Guillaume','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CROZAT','Alex','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DAKHLI','Ines','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DAMON','Marguerite','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DANIELLOU','Cécile','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DAVID','Alexandre','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DE MILLEVILLE','Guillaume','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DE PONTAC','Philippe','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DE ROSNAY','Inès','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DEBRIS','Caroline','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DECRÉ','Sohalia','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DELAGE','Claire','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DELATTE','Bérénice','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DEMETZ','Alexis','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DESBRUERES','Anaïs','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DESLOGES','Romain','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DEZONS','Charles','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DIALLO','Aminata','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DJEFFAL','Nahel','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DONIUS','Corentin','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DRUETTE','Ludovic','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DUCHENE','Augustin','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DUFOUR','Hélie','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DUFOURD','Noémie','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DUHALDE','Mélisande',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DULOUT','Sacha','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DZIK','Eliel','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ECOIFFIER','David','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('EL MADANI','Jad',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('FARGES','Paul','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('FERRERI','Cécile','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('FOURNEL','Arthur','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('FOURRIER','Clara','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('FREDHOLM','Nathan','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GARNIER','Sophie','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GÉRARD','Romain','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GÉRARD','Garance','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GERAZ','Pierre','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GILBERTAS','Florian','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GIORDANI','Lola','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GIRARDOT','Mathilde','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GIROUSSE','Gaëlle','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GLÉNARD','Clémentine','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GODARD-CADILLAC','Silène','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GOSSELIN','Erwan','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GOSSELIN','Maxence','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GOVIGNON','Charlotte','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GRABSIA','Stéphane','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GRELET','Maxime','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GRELLIER','Léonard',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GUENIFFEY','Baptiste','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GUIDOLLET','Elouen','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GUILLONNEAU','Raphaël','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GUIPAUD','Simon','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HAJLAOUI','Hayder',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HAMOUD','Abderrezak',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HAMZAOUI','Mohammed-Taha','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HENON-JUST','Guillaume','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('INGBERG','Lucas',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('JEANSELME','Baptiste','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('KEMGNE','Chloé','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('KERNEUZET','Roxane','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LAMARQUE','Arnaud','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LAMBRECHT','Grégoire','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LANCELOT','Tatsumi','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LANGLADE','Lucas','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LAPORTE','Michaël','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LAROCHE','Simon','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LBARCH','Abd',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LE BOUTEILLER','Claire-Alix','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LE CLERC','Léandre','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LE GOFF','Pierre-Louis','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LE ROMANCER','Briac','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LE ROUX','Adrien','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LE VOT','Valentine','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LEJEUNE','Florentin','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LEMAIRE','Paul','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LEPERS','Abigaïl','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LEQUEUX','Marlone','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LINDEGAARD','Tanguy','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LIU','Cécile','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LODS','Gaspard','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LOGEROT','Antoine','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MARIETTE','Angèle','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MARTINET','Hector',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MASSEI','Thomas','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MATTATIA','Joséphine','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MAUCHARD','Nicolas','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MÉRIGOT-LOMBARD','Matthieu','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MERLEN','Gauthier','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MICHETTI','Marius',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MONTANE','Eve','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MOREAU','Foucauld','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MORENO','Pablo','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MORIN','Jacques','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MOTHE','Axel','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MUCHA','Quentin','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MULET','Clément','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('NAIT CHABANE','Heddi','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('OBLIN','Gautier','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('OLIVIER','Antoine','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ONDOUA','Angèle','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ORY','Clément','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('OUBOUJEMAA','Achraf','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('OVAZZA','Noam','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PAPY','Cédric','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PATINIER','Gaëtan','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PERY','Mattin','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PIC','Emilie','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PIONNEAU','Clément',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PLADO COSTANTE','Loucas','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PONCET','Bastien','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('POULAIN','Louis','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('POUSSY','Louis','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PRÉTER','Mathis','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('RAMANANTSOAVINA','Tanguy','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('RENIER','Jeremy','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('REROLLE','Matthieu','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('RICHARD','Willem','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('RIVET-TISSOT','Anaximandre','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ROLLAND','Eloïse','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ROQUEFORT','Filomène',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ROUDNINSKI','Samuel','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SANGUINET','Colin','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SAUTIER','Lucas','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SCAON','Hugo','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SCHMITT','Loris','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SELLABI DIT CHALABI','Yanis','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SEREYJOL-GARROS','Nicolas','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SILBERZAN','Matthieu','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SIMON','Nathan','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SIRCAT','Dimitri','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SOHM','Mel','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SOUYRI','Thaïs','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('TANG','Gabriel','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('TAZI','Sara','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('THERAUD','Romain','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('TISSOT','Mathieu','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('TRAM','Tri Minh','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('TRAN','Brandon','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('USWATTA LIYANAGE PERERA','Chamod','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('VANLAEYS','Inès','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('VERDIER','Valentin','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('VIRELIZIER','Arnaud','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('VOILLAT','Hilaire','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('VU QUANG','Bérénice','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('WAQUET','Louise','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('WATERS','Hugo','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('WICHLACZ','Léo','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('YANN','Hélène','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ZAKHARIA','Jad','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ZEGOUAGH','Elias','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ZERHOUNI','Maude','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LOPES MACHADO','Kelly',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MARQUES PHILOMENO','Luis Fernando','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DONZIS','Sebastian Ariel','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SANCHEZ AREVALO','Maira Alejandra','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('VALLEJO RIOS','Nicolás','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('EL LAHAM','Salwa',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('EL SABBAGH','Justin',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('KAYALE','Abdo',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('RICHA','Rita',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SAADEH','Christian',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DINU','George-Daniel','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LOPEZ DE SUBIJANA ESTEBAN','Iratxe','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ZUBIA PALAZUELOS','Pablo','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PHAN','Xuan Truong',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('VU','Thi Phuong',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ABOUHARIA','Younes',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('EZBIRI','Malake',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MNACHCHAT','Othmane',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LARE','Gbanfoulene',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GRANTE','Axel','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('KAMINSKAS AZAR','Karsion Habib','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MOZAFARI BIDGOLI','Mohammadreza',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ABBASSI','Chaima',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DIALLO','Alhassane','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ADMAMOU','Hiba','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LUO','Zhongchang','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('QIU','Changhao','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('XU','Zhaochen','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MEMBRILLA ALONSO','José','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BAUDELLE','Chloé',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CONVERT','Antoine',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('JOURNO','Tiphaine',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LACH','Baptiste',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LECOMTE','Alexiane',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ALLOYER','Amaury','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ARNAUDO','Etienne','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BAUDU','Marion','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BEN LOLO','Ivan','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BENVEGNEN','Tom','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BERTHOU','Lise','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BICHARD','Gauthier','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BOURGEOIS','Antonin','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CHARRADE','Pauline','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('COLLET','Gaétan',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DANEL','Hector','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DE LEUSSE','Theodore','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DE MEULEMEESTER','Hector',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DE SEZE','Blandine','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DEHAIS','Solène','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DELOR','Jeanne','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('D''HERBOMEZ','Alexis','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DUBERTRET','Marguerite','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GALAND','René','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GALLOT','Salomé','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GEORGES','Etienne','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GUILLEMIN','Théo',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HÉZARD','Chloé','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LAMBARD','Pierre','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LEFEBVRE','Justine','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LORNE','Bertrand','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('POIZAT','Arno','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ROUSSET-ROUVIERE','Louis-Mayeul','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SANCHEZ','Clara','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('TABACHE','Hatim',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('THAI','Julie','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('TREZARIEU','Raphaël','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('VENDE','Jim','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('VILLAIN','Arthur','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ZUGARRAMURDI','Lukas','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LEVY','Yohann',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SADEK','Jad','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ALLO','Blaise-Pascal','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ZHA','Rui',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HARMAND','Thomas',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LE GRAND','Elouan',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('COSTA CAMPOS DE MOURA','Murilo','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MAHDAOUI','Mahdi',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LISSIGUI','Asma',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ZERKA','Imane',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('FERREIRA FORMOSO DA SILVA','Isabel','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BOURDIN','Océane','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DEL''AGUILA','Luc','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('D''ELISSAGARAY DE JAURGAIN','Antton',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('FILLOUX','Auguste','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HARLAY','Mathieu','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MERRIEN','Matéo','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ARCHAMBAULT','Jeanne','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BAFFOS','Clément',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BÉLIGON','Thomas',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BEN ABDELLAH','Mohamed Amine',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BOILLY','Louis','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BORNERT','Anna','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BOUDIA','Rayan','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BUIRON','Thomas','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CASANOVA','Guillaume',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DERVILLE','Tanguy','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HEALEY','Holly','L');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LALEUW','Victor','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LAMORY','Clément','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LEGOUPIL','Noël','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LEMAITRE','Clara',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MALINVAUD','Domitille','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MEUNIER','Simon','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PARENT','Nil','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PARIS','Louis','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PASCAL','Timothée','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ROQUES','Mathieu','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SÉVÉRAC','Romane','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('THOMAS','Sonia','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DE FAUTEREAU-VASSEL','Hugues',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HOU','Xiaohang',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('YANG','Ping''an',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('AOUN','Cyril',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BOUZID','Ahmed','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BENKIRANE','Badr',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ORBERG TEMER','Barbara',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PYRYT','Benjamin','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HEINZELMEIER','Katia','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BRUNEAU','Valentin','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CAPILLON','Sébastien','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('COCUSSE','Marion','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GARON','Josua','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('KRATZ','Benjamin','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LACOURT','Aurélien','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MAIRESSE','Emmanuel','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PENNEL','Romain',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PEYROT','Guirec','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PIARD','Justine','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ROSALES','Matteo','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SAUGIER','Idriss','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('TREGER','Teiva','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BELIN','Matthieu','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BLANKEN','Karel','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BRUN','Camille','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('COULOMBEL','Pierre','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CRAMBERT','Alix','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DANIS','Ludovic','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DROVETTI','Pierre-Hugues','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('FLAJOLLET','Titouan','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('FORTIER','Antonin','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GALIÈGUE','Louis','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GAY','Robin','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GOLDSCHMID','Louis','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('KOWALCZYK','Clara',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LABROSSE','Tom','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LE MOING','Mathilde','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LEPAITRE','Benjamin','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MONTOIS','Maxime','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MOREL','Enora','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MORILLON','Arthur','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PERRON','Thomas',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('RAVAUD','Tom','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('RIGAUD','Alexandre','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('RUAUX','Marie',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SAIAS','Clémence','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SPONEM','Léa','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('TOCHON','Louis','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('TOQUEBOEUF','Camille','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('VOILLOT','Paul',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LECLEVE','Théo',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('THIMONIER','Tom',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('JOORIS','Baudouin',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BENOIST','Emeric',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LEMEUNIER','Vincent',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('XIAO','Haotian',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('YIN','Guoqing','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ZHOU','Shuhang','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('VATI','Inès','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ANTONETTI','Mathis',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ARTHAUD','Majid','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BRELIVET','Lucas',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CHASSARD','Martin',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('EZZEHI','Sofiane','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('KAREMBE','Maël',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LE GUERCH','Thomas','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('AKHANNOUSS','Manal',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BOYER','Margot','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CAPGRAS','Justin','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DUVAL','Benoit','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GALLO','Francesco',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HAMMANI','Salma',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('INVERNIZZI','Paul','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PESNEC','Amélie','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('TAISANT','Raphaël','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('TRENQUIER','Eloi','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('VAN OVERLOOP','Hannes',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BASTIAN','Arnaud','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BERTRAND','Cyril','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CHERGUI','Inès',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CIRON','Pierre-Marie','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ELKOUBI','Sacha','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GOURIO','Charles-Auguste',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('KAHAN','Raphaël','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LECOUTRE','Jérémie','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LEGENDRE','Maxim','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('POMIÈS','Nikita-Marc',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SAYAH','Ramzi',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SÉNÉGAS','Michel','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('WAN','Alexandre',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ANADON','Cécile',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BARBIER','Paul',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('COLLIN','Joachim','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DUNOYER DE SEGONZAC','Joy-Rose','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('FERRERES','Elodie',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LARROCHE','Inès','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LE CHENADEC','Bastien','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LUTT','Alexandre',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MARTIN','Tristan','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MATENCIO','Even','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MENOURET','Nicolas',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PIGEARD','Mehdi-Lou','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PINSOLLE-BOURTAYRE','Henri','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('RISOLA','Thomas',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('TERRISSE','Theïlo','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('VOGLER','Prunelle',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HEIBIG','Jean',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('AYMANE','Nohair',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CAHU','Arthur',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('KHATOURI','Zouhair',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PARAVY','Valentin','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DUAN','Senhao',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ZHANG','Yiling','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DUTOT','Grégoire',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MIRAS','Cyril',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SÉPULCHRE','Thomas',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CARRIZO','Andrés',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BAZIN','Gabrielle','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BERRAHMA TLEMCANI','Mamoun','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GAIGNARD','Quentin','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('METZ','Nathaël','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PETRILLI','Hugo','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BAZILLE','Cyprien',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BEYE','Lilian','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BOUBEKRI','Nouhayla',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BOUILLOUX','Mathilde','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BRODIN','Laëtitia','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CATIMEL','Timothé','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CHALTIEL','Fanny','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CHEVALLEY','Xavier','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DESHORS','Guillaume','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DUJARRIER','Arnaud','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('DUJARRIER','Chloé','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ELBOUNSRI','Widad','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('FRANCHINO','Thibault',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('FRECAUT','Guillaume',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HAZOUARD','Alexis','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MARTIN LAPRADE','Eve','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MEYNARD','Mathieu','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('NAHMIAS','Maïmone',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PISTOLESI','Giulio','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PLANES','Théodore',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('RIVIÈRE','Damien','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SICARD BENMEDJAHED','Clara','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('TRUONG','Bao-Trân','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('VOISARD','Pierre','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LIN','Zinan',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ARAUJO MACHADO DE CASTRO FEITOSA','Sarah','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('FIORITO FRANCO PIRES','Giovanna',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CARREGOSA DO PRADO','Matheus Luiz','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GUANAES ROSETTI','André','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('AMIEVA ZUCAL','Milagros','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MERINO MARTINEZ','Fernando','S');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CHIBANI','Youssef','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MANGET SÁNCHEZ-SACRISTÁN','Cristina','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HADDAD MARUM','Mateus','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('TURRI TAVARES','Thiago','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GHASEMI','Ahmadreza','Z');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('KHOSHNAM','Reza','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('SAMAEI','Maryam Sadat',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('NAKAZAWA','Yugo',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HIGASHINO','Masanobu','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('PASTOR SERRANO','Daniel','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('ATTOLOU','Laureen','D');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('TRAMONI','Julien','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('TRAN-HEINERICH','Tiffany','W');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GUILLOTIN','Léo',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('LOUAZEL','Justin','C');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MENAOUI','Aymen',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('FERRY','Pierre','M');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HEBEL','Hugo','A');
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CHAZELLE','Guillaume',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HAULON','Arthur',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('APPEL','Nicolas',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MA','Yinghua',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BAALI','Mehdi',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('HAZOUME','Théophane',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BSALIS','Carl',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('BOULANGER','Matthieu',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('GOUPIL','Antoine',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('CREUSÉ','Eulalie',NULL);
INSERT INTO `familles`(`Nom`,`Prenom`,`Famille`) VALUES ('MARANDET','Odile',NULL);
